ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "emailVerified" TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS image VARCHAR(255);
ALTER TABLE user_xp ADD COLUMN IF NOT EXISTS prestige_level INTEGER DEFAULT 0 NOT NULL;
